# Generated by Django 4.2 on 2023-04-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie", name="year", field=models.CharField(max_length=100),
        ),
    ]
