# Generated by Django 4.2 on 2023-04-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_movie_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie", name="runtime", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="movie", name="title", field=models.CharField(max_length=1000),
        ),
    ]
