# Generated by Django 4.2 on 2023-04-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_movie_runtime_alter_movie_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie", name="budget", field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="movie", name="revenue", field=models.IntegerField(null=True),
        ),
    ]
