# Generated by Django 4.2 on 2023-04-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_movie_budget_movie_revenue"),
    ]

    operations = [
        migrations.RemoveField(model_name="movie", name="budget",),
        migrations.RemoveField(model_name="movie", name="revenue",),
        migrations.AddField(
            model_name="movie",
            name="gross_millions_of_dollars",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
