# Generated by Django 4.1.7 on 2023-03-30 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_movie_trailor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='lang',
        ),
    ]
