# Generated by Django 4.2 on 2023-04-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_movie_runtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
