# Generated by Django 4.2 on 2023-04-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_alter_movie_rating"),
    ]

    operations = [
        migrations.RemoveField(model_name="movie", name="trailor",),
        migrations.AddField(
            model_name="movie",
            name="trailer_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
