# Generated by Django 4.2 on 2023-04-22 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_rename_trailer_link_movie_trailer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie", old_name="trailer", new_name="trailor",
        ),
    ]
