# Generated by Django 4.2 on 2023-04-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_rename_trailer_movie_trailor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="trailor",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
