# Generated by Django 4.2 on 2023-04-23 13:06

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_alter_movie_trailor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie", old_name="gross_millions_of_dollars", new_name="budget",
        ),
        migrations.AddField(
            model_name="movie",
            name="revenue",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="lang",
            field=models.CharField(default="English", max_length=100),
        ),
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="trailor",
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
