# Generated by Django 4.2 on 2023-04-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_rename_gross_millions_of_dollars_movie_budget_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="movie", name="year", field=models.CharField(max_length=15),
        ),
    ]
